[package]
name = "sqlant"
version = "0.1.0"
edition = "2021"

[dependencies]
postgres = "0.19.3"
tinytemplate = "1.2"
serde = { version = "1.0", features = ["derive"] }

[profile.release]
opt-level = "z"  # Optimize for size.
strip = true
lto = true
